DATA:
  name: "SA128"
  img_size: 128
  num_classes: 221
PRE:
  apply_rflip: False
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "D2DCE"
  normalize_d_embed: True
  d_embed_dim: 768
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [4]
  attn_d_loc: [1]
  z_dim: 120
  g_shared_dim: 128
  g_conv_dim: 64
  d_conv_dim: 64
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  adv_loss: "hinge"
  cond_lambda: 1.0
  m_p: 0.98
  temperature: 0.5
OPTIMIZATION:
  batch_size: 128
  acml_steps: 1
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 20000
