DATA:
  name: "SA64"
  img_size: 64
  num_classes: 221
PRE:
  apply_rflip: True
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [3]
  attn_d_loc: [1]
  z_dim: 100
  g_shared_dim: 128
  g_conv_dim: 64
  d_conv_dim: 64
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  adv_loss: "hinge"
  apply_cr: True
  cr_lambda: 10.0
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1
  total_steps: 40000
AUG:
  cr_aug_type: "cr"

